import { ParcelCodes } from "./types";
import { Client } from "./client";

describe('client', () => {
  const client = new Client();

  const codes1 = [ParcelCodes.Fragile];
  const codes2 = [ParcelCodes.Fragile, ParcelCodes.DoNotLeave];
  const codes3 = [ParcelCodes.Fragile, ParcelCodes.DoNotLeave, ParcelCodes.ReturnReceiptRequested];

  it('should return delivery details with autogenerated ID and calculated price based on fromZipCode', () => {
    const simpleShipment = client.requestShipment({
      weight: 20,
      fromAddress: '12292 4th Ave SE, Bellevue, Wa',
      fromZipCode: '92021',
      toAddress: '1313 Mockingbird Lane, Tulsa, OK',
      toZipCode: '67721',
    });

    expect(simpleShipment).toBe(
      `Shipment with the ID 1 will be picked up from 12292 4th Ave SE, Bellevue, Wa to 1313 Mockingbird Lane, Tulsa, OK\nCost = 3.8`);
  });

  it('should return delivery details and calculated price based on fromZipCode and special code', () => {
    const shipment1 = client.requestShipment({
      shipmentID: 12245,
      weight: 4,
      fromAddress: '12292 4th Ave SE, Bellevue, Wa',
      fromZipCode: '92021',
      toAddress: '1313 Mockingbird Lane, Tulsa, OK',
      toZipCode: '67721',
      }, codes1);

    expect(shipment1).toBe(
      `Shipment with the ID 12245 will be picked up from 12292 4th Ave SE, Bellevue, Wa to 1313 Mockingbird Lane, Tulsa, OK\nCost = 2.04\n**FRAGILE**`);
  });

  it('should return delivery details and calculated price based on fromZipCode, parcel type and special code', () => {
    const shipment2 = client.requestShipment({
      shipmentID: 92985,
      weight: 200,
      fromAddress: '42292 4th Ave SE, Bellevue, Wa',
      fromZipCode: '12021',
      toAddress: '1313 Mockingbird Lane, Tulsa, OK',
      toZipCode: '67721',
      }, codes2);

    expect(shipment2).toBe(
      `Shipment with the ID 92985 will be picked up from 42292 4th Ave SE, Bellevue, Wa to 1313 Mockingbird Lane, Tulsa, OK\nCost = 88\n**FRAGILE**\n**DO NOT LEAVE**`);
  });

  it('should return delivery details and calculated price based on fromZipCode, parcel type and aggregate special codes', () => {
  const shipment3 = client.requestShipment({
    shipmentID: 54345,
    weight: 200,
    fromAddress: '52292 4th Ave SE, Bellevue, Wa',
    fromZipCode: '82021',
    toAddress: '1313 Mockingbird Lane, Tulsa, OK',
    toZipCode: '67721',
    }, codes3);

    expect(shipment3).toBe(
      `Shipment with the ID 54345 will be picked up from 52292 4th Ave SE, Bellevue, Wa to 1313 Mockingbird Lane, Tulsa, OK\nCost = 106\n**FRAGILE**\n**DO NOT LEAVE**\n**RETURN RECEIPT REQUESTED**`);
  });
});
